### ISSUE TITLE
Docker image does not match Github

### ISSUE THREAD

**Issue by pwrightkcl** [MS-PINPOINT/mindGlide#15]
The code in Docker image armaneshaghi/mind-glide:latest does not match the code in Github at time of writing.

Specifically, the function 'generate_random_string' moved from 'run_inference.py' to 'ensemble_utils.py' in Github but not in the image, so the imports failed when I tried to use an edited version of 'run_inference.py' from Github. I think the commit that made this change was on 3 Apr.

**Comment by armaneshaghi** [comment]
The solution is to connect `dockerhub` to Github actions , on my to-do list.
