### ISSUE TITLE
Alternative way of building .sif image?

### ISSUE THREAD

**Issue by ChristineFarrugia** [MS-PINPOINT/mindGlide#31]
Hi,

Apologies for opening another issue, but I am very happy with my first MindGlide results and would like to use it further. Before I do, however, I just want to make sure I've built the correct image. I'm using Apptainer as Docker cannot be installed on our server. At first I tried to follow the instructions on your homepage and build the Apptainer image using another Docker container (via the Docker installation on my workstation), but ran into issues. One of the system admins suggested the following:

`apptainer build ${APPTAINER_TMPDIR}/mindglide.sif docker://armaneshaghi/mind-glide:latest`

where ${APPTAINER_TMPDIR} is the temporary directory used during the build. I've been using the resulting .sif file thus far and have not encountered any problems, but I'd like to verify this approach doesn't introduce any changes in the .sif image. 

Many thanks in advance,
Christine

**Comment by phiphi0815** [comment]
Hi Christine,

I just tested your approach and could not see any changes compared to the .sif file we use. So please feel free to use it this way. Let us know if you encounter any problems or if you want to discuss your results.

Thank you for using MindGlide; we hope it helps your analysis.

Best wishes,
Philipp
